### ISSUE TITLE
Add Agenda/list view

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#11]
Hi,

maybe I missed the feature so far but is it possible to have sort of like a agenda view? If you use multiple calendars and tags it come most handy to have a "listed" view on events and not just the already present views like day, week, etc.

Great work!

**Comment by libasys** [comment]
list view is available! look on the settingsdialog of the calendar, here you can activate your views!

**Comment by Tramour** [comment]
Just found out myself and wanted to let you know that my issue is solved ;-). 
Thanks
