### ISSUE TITLE
Add possibility to print views

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#12]
Is it possible to add a print functionality to the calendar app?

**Comment by libasys** [comment]
How should this look like, for the best way? some short description, please!

**Comment by Tramour** [comment]
In my company we use MS Outlook. Can you take a look at that printing-capability? 
Maybe different templates for the different views accessible? At least a possibility to print the list view with range from date x to date y for starters.

**Comment by libasys** [comment]
I have no outlook, can you attach a pdf for the single views, so i can show up how outlook do this!

**Comment by Tramour** [comment]
Couldn't upload a pdf-file. It's not allowed. Will upload JPG tomorrow.

**Comment by libasys** [comment]
ok! Thanks for your work!

**Comment by Tramour** [comment]
![monat](https://cloud.githubusercontent.com/assets/13016794/8314418/baa192a4-19e9-11e5-8e31-718c060cfb55.jpg)
![printerdialog](https://cloud.githubusercontent.com/assets/13016794/8314420/baaed0b8-19e9-11e5-80f1-9b9a84b43235.jpg)
![tagesformat](https://cloud.githubusercontent.com/assets/13016794/8314419/baacf090-19e9-11e5-9f20-f9851c272df2.jpg)
![woche](https://cloud.githubusercontent.com/assets/13016794/8314422/bab7d8a2-19e9-11e5-9b6a-19f48db9acc1.jpg)
![wochenagenda](https://cloud.githubusercontent.com/assets/13016794/8314421/bab3a804-19e9-11e5-9c04-274fad88de0c.jpg)
