### ISSUE TITLE
Add checkboxes for tags for easy searching/filtering

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#13]
At the moment when you click a tag the appropriate events flash. For filtering it would be very useful if checkboxes were available.

**Comment by libasys** [comment]
And what should do the checkboxes by clicking? Please more details!

**Comment by Tramour** [comment]
Just view the events where the checkboxes are checked. Like the calendars. Thus in list view I can "filter" all events which are tagged for example "Arbeit" and/or "Feiertag" and/or "Ideen". Or whatever tags people create. 
Example: I have one personal calendar, one calendar for my wife and a family calendar. For my children I use tags. When I want to see events concerning my children I can check "son 1" and/or "son 2". 

The results of the search functionality are not very user friendly to evaluate concerning events and it does not support tags to be searched for.

**Comment by libasys** [comment]
Ok, this is an enhancement! It comes to my todo list!
