### ISSUE TITLE
Popup doesn't close after clicking <OK>

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#14]
RC8.1
PHP 5.4
Latest Calendar version from today

After creating an event popup doesn't close after clicking OK-button. Multiple events with the same content created. Only <cancel> closes popup.

**Comment by libasys** [comment]
Please add more info to your Bug Reports! What says the logs on the Admin settings Page! What is your Environment ? Apache MySQL etc! What says the js error Log of your Browser? Thanks!

**Comment by Tramour** [comment]
Updated PHP to 5.5, Apache MySQL 5.6.23
Here's a picture of the js error log
![screenshot 2015-06-24 15 36 07](https://cloud.githubusercontent.com/assets/13016794/8331147/00a7ca96-1a87-11e5-8d77-9274413117eb.png)

And her's the admin log:
![screenshot 2015-06-24 15 39 06](https://cloud.githubusercontent.com/assets/13016794/8331182/39a54dfa-1a87-11e5-9a6b-4496aa740057.png)

**Comment by libasys** [comment]
you have setup your timezone in the calendar settings to Europe/Berlin ?

**Comment by Tramour** [comment]
Yes.

**Comment by libasys** [comment]
It could be a problem of php5.6! i have to investigate for this issue! My test environment currently running under php5.4!

**Comment by ghost** [comment]
I will spend time for testing this issues starting this evening but currently i am travelling back home.

**Comment by libasys** [comment]
@criegerde i tested event creation on your cloud and all works well! @Tramour i think is a problem of php5.6! can you test your cloud with php5.4, or not?

**Comment by ghost** [comment]
My cloud is running on php5.6 either

"AddHandler php56-cgi .php"

configured few minutes ago

**Comment by Tramour** [comment]
I'm not running on PHP 5.6 --> mine is PHP 5.5.22 (not CGI)
MySQL is 5.6

**Comment by Tramour** [comment]
test.famibos.de

Testaccount created: user and pwd libasys

If you are interested anyway...

**Comment by libasys** [comment]
ok! Thanks! I have tested and i can create new events! Have no problems! i am on a mac with firefox!

**Comment by Tramour** [comment]
My first tests yesterday were with PHP 5.4 (post #1). I had All ink update to PHP 5.5 over night.

**Comment by Tramour** [comment]
Can you create some dummy calendars and create events there too? I gave you access to one of my calendars. Can you create an event there?

And does the OK-Button work?

**Comment by Tramour** [comment]
Chrome with Win8 on my side...

**Comment by libasys** [comment]
ok can test with mac chrome, but all works well with FF

**Comment by libasys** [comment]
mac chrome works fine!

**Comment by Tramour** [comment]
Tried IE11. Same prob: OK-Button does not work...

Found out the following: After creating an event an pressing OK nothing happens. But after refreshing the page with F5 the event is created in calendar.

**Comment by libasys** [comment]
i have no windows pc for testing!

**Comment by Tramour** [comment]
Hm. All works fine under 8.0.4. Serverside and browser are the same...
@criegerde Are you running windows?

**Comment by libasys** [comment]
on 8.0.4 the calendar app is a complete different version to this!

**Comment by Tramour** [comment]
Of course. I just wanted to point out that the server and browser work under that setting and nothing has changed on that side..

**Comment by Tramour** [comment]
@libasys  Can you create a calendar and share it with me? I try to create an event there.

**Comment by libasys** [comment]
i shared some calendars with ralf.boss is that correct?
You should be able to see Kalender More Fun!

**Comment by ghost** [comment]
Both windows 8.1 x64 and ubuntu 14.04 LTSx64
Will test both systems and give you a response

**Comment by Tramour** [comment]
@criegerde  you can access test.famibos.de with criegerde and criegerde if you want to.
Maybe you can reproduce the situation...

**Comment by Tramour** [comment]
@libasys  Thanks fpr sharing. Created events in both your shared calendars but OK doesn't work properly. After F5 all is fine....

**Comment by libasys** [comment]
my tests all ok, so i think we have to wait fo @criegerde testing from a ms machine!

**Comment by Tramour** [comment]
Ok.
@libasys Does it help you to have access to OC installation on server via ftp?

**Comment by libasys** [comment]
not at the moment, we have to wait if he confirm this fault, or not!

**Comment by ghost** [comment]
online again
i shared two calendar, one was new created (criegerde02) and shared to both of you, ralf.boss and libasys.
![02](https://cloud.githubusercontent.com/assets/12971682/8338066/c663d942-1aae-11e5-8a17-379dbd584cac.JPG)

I created to new events and was shareing them to both of you.

I was not able to edit the color of the new created calendar
![01](https://cloud.githubusercontent.com/assets/12971682/8338070/d347e27a-1aae-11e5-96d6-8d45e638e589.JPG)

What should I test in detail?

**Comment by Tramour** [comment]
When you create an event on my OC does the OK-button work properly -> close and show created event in calendar without having to use F5?

**Comment by ghost** [comment]
yes, without F5

**Comment by Tramour** [comment]
In @criegerde ID10 calendar I can't create any events. In ID11 it is possible.

**Comment by Tramour** [comment]
Ok. So it seems to be just my problem and it works for you both in my OC.

**Comment by ghost** [comment]
but adding a tag in your calendar/your event failed
![03](https://cloud.githubusercontent.com/assets/12971682/8338230/28549ffa-1ab0-11e5-8321-dbe1cb9ae603.JPG)

**Comment by libasys** [comment]
change color on edit calendar, this bug is confirmed and is known, will be fixed with next version on git!

**Comment by ghost** [comment]
fyi: both calendars were shared with full rights

**Comment by ghost** [comment]
20:36:42.468 TypeError: Calendar.popOverElem is null1 calendar.js:1459:4
I had to cancel the altering of the event but neither OK nor cancel leads to a closed window

**Comment by libasys** [comment]
ok this is also a known issue! Sometimes the popover looses his target, but i think the popover dialog is much better than the old dialog, or not?

**Comment by ghost** [comment]
for sure!

**Comment by ghost** [comment]
from my point of view it works fine
anything else to test or investigate?

**Comment by libasys** [comment]
at the moment from my side not!

**Comment by Tramour** [comment]
Hm. Anything I can add to my written observations? For me it still doesn't work properly to create new events (one last image with js error log):
![screenshot 2015-06-24 21 26 56](https://cloud.githubusercontent.com/assets/13016794/8339455/d426467e-1ab7-11e5-8b8a-25dce7775027.png)

@libasys If you need access or more information, let me know.
@criegerde Thanks for testing.

**Comment by Tramour** [comment]
After having solved the "Where-are-my-icons-and-settings-problem" I still can't "ok" new events. All that helps is to refresh the page manually with F5. Still doesn't work with my Chrome (tested at home and at work).
@libasys Can you create events in the normal and expected way?

**Comment by libasys** [comment]
ok please reset my password my new password not works! reset to old one! thanks!

**Comment by Tramour** [comment]
Done.

**Comment by libasys** [comment]
can't login!

**Comment by Tramour** [comment]
Great. Changed you pw. Obviously did not work. Killed your account. tried to set it up again. Did not work with same username!
New access: test2, test2

**Comment by libasys** [comment]
ok

**Comment by libasys** [comment]
no problem with new event creating! Have you popup blocker or similar activated? can you add a new event by pressing enter after you entered the title?

**Comment by Tramour** [comment]
Enter doesn't close popup. But after F5 the event is there. 
Popup blocker? Not that I know of. I try it again with IE11...

**Comment by Tramour** [comment]
It works with IE11 at work. Perfect. Now I just have to figure out how it works at home with my chromio!

Thanks.

**Comment by ghost** [comment]
Doesnt work for me in IE. I disabled the popup blocker in chrome and tested again, same outcome: OK not clickable. Thats on Windows..

Everything is fine with my Macbook, OK is clickable.

**Comment by libasys** [comment]
I think there is some setting on your pc which blocks that popup, it is interesting which setting it is! Have you some js error etc?

**Comment by ghost** [comment]
Yes, I got an error. It appeared after clicking on OK. Funny enough, deleting the test post after refreshing the page with F5 works :)

![untitled](https://cloud.githubusercontent.com/assets/13250962/8590499/87a9af8c-2621-11e5-95f7-fab47d620507.jpg)

**Comment by libasys** [comment]
If you add a new event and pressing enter, the popup should be close! Work this?

**Comment by ghost** [comment]
unfortunatly, pressing Enter instead of clicking OK doesn´t work. When pressing Enter and refresh, Entry appears. Pressing Enter in the delete entry popup works. It seems that just the create entry popup is affected.

**Comment by Tramour** [comment]
@libasys I still have the same problem like @edelrost. 8.1 RC2 otherwise same setting as the last times (using chrome). I installed the "original" calendar app as well and there everything works fine (klicking and pressing enter).
You can give it a try at test.famibos.de; test and test.

**Comment by libasys** [comment]
@Tramour popup works! but not the settingsdialog, no error, but could happen cause you have a task which breaks a lot of stuff, can you paste the ics of "02.07.2015 18:00 Feuerwehrwochende" there are some problems with datetime!

**Comment by Tramour** [comment]
i just wanted to open another issue for the setting button ;-)
I'll check the database.

**Comment by libasys** [comment]
can you update the calendarplus app to 1.0.1. on appstore is the zip available https://apps.owncloud.com/content/show.php/Calendar+Plus?content=170560

**Comment by Tramour** [comment]
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar 1.0.0
BEGIN:VTODO
DUE;TZID=Europe/Berlin:20150702T180000
CREATED:20150630T170255Z
LAST-MODIFIED:20150630T170340Z
DESCRIPTION:\n[ ] Klamotten\n[ ] kein Bettzeug\n[ ] Badesachen\n[ ] Hygiene
 artikel\n[ ] DKV-Karte
SUMMARY:Feuerwehrwochende
PRIORITY:1
PERCENT-COMPLETE:100
STATUS:NEEDS-ACTION
DTSTAMP:20150630T170342Z
UID:8a440529-3e4a-4d44-a2ca-78d7d479b8af.1435683822209
END:VTODO
END:VCALENDAR

**Comment by libasys** [comment]
thanks, i will test it

**Comment by libasys** [comment]
what is your desktop client if you add events or tasks?

**Comment by Tramour** [comment]
It is an android app named  Tasks by Marten Gajda. Works like a charm.
