### ISSUE TITLE
Can't create new events

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#15]
Imported icals from 8.0.4. It is just possible to create events in one calendar (Dienst). The other ones do not work. 
![screenshot 2015-06-23 21 26 39](https://cloud.githubusercontent.com/assets/13016794/8315162/db752086-19ee-11e5-9aae-a480c0e55056.png)

**Comment by libasys** [comment]
Please add more info to your Bug Reports! What says the logs on the Admin settings Page! What is your Environment ? Apache MySQL etc! What says the js error Log of your Browser? Thanks!

**Comment by libasys** [comment]
Please could you give a short feedback what solved your problem? Thanks!

**Comment by Tramour** [comment]
You're latest version did the trick. Now I can create events with all calendars.
