### ISSUE TITLE
Strange popup after clicking on calenda view

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#17]
When I open an already existing event
![screenshot 2015-06-24 20 31 11](https://cloud.githubusercontent.com/assets/13016794/8338278/75484f32-1ab0-11e5-89fe-29bad795bdac.png)

and then do NOT use Abbrechen or OK but simply click on a new date in the view I get the following cut-off popup (upper left):
![screenshot 2015-06-24 20 26 10](https://cloud.githubusercontent.com/assets/13016794/8338331/c71d0aa0-1ab0-11e5-9e7f-ad636eafd346.png)

@libasys Can you reproduce this behaviour in my OC or yours?

**Comment by libasys** [comment]
yes is confirmed! would be fixed with next version of calendar. this sometimes can happend, cause this is a brand new top feature and needs to granulate! Thanks for the bug report!

**Comment by Tramour** [comment]
Thanks.Can be closed.
