### ISSUE TITLE
Make range for date in list view adaptable

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#18]
List view offers a two-week-window which starts alway on monday.

I'd appreciate it very much to have the possibility to set a start and end date for this view. 

Furthermore a view like an agenda would be possible (start today and in the future).

**Comment by libasys** [comment]
choosing a range via a selectbox like 2-weeks, 4-weeks preview?

**Comment by Tramour** [comment]
Sounds good. Should be possible for the past as well (so I can have a "filtered" look at specific events like meetings). Or offer an start time calendar and end time calendar to pick the dates.
