### ISSUE TITLE
No GUI in latest version after fresh install

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Calendar-App#21]
I  setup latest build of OC with your latest calendar version. But the GUI is missing.
![screenshot 2015-06-26 22 09 31](https://cloud.githubusercontent.com/assets/13016794/8386424/8308abde-1c50-11e5-9597-3ba20dd831cd.png)
No errors in OC log and in js.
Task and gallery are running smoothly.

**Comment by Tramour** [comment]
Created second user without admin rights. And again no UI.

**Comment by ghost** [comment]
I did an uninstall of 1.0.2 an a new install of 1.0.3. 
Can not confirm the issue. 
Are you able to configure the calendar or does it disappeare too?

**Comment by Tramour** [comment]
I can't find any icons to configure the calendar (compare screenshot). That's all I got.

**Comment by Tramour** [comment]
Hm. It was a fresh install with the latest daily build of OC and calendar 1.0.3...

**Comment by ghost** [comment]
Did you deactivate the app, remove the files from /apps, reinstall and finally reenable the app. 
I am on ubuntu and firefox for testing.

**Comment by Tramour** [comment]
We are both hosted by all inkl. I've got the same server setting ;-)
To answer your question: I guess I did so. But anyway I will again setup OC new with fresh MySQL and try one last time. 

Ubuntu and Chrome on a Win8.1x64

**Comment by Tramour** [comment]
Steps to reproduce
1. Install latest daily build of OC
2. Create admin on MySQL 5.6.24
3. Run OC
4. Check apps -> no calendar app activated or to be activated
5. Log off
6. Unzip calendar app in /apps
7. Move dir calendar from /ownCloud-8.1-Calendar-App-masterv to /apps
8. Login to OC with admin
9. Activate Calendar Advanced  1.0.3
10. Go to calendar ->same picture as my first post -> nothing to adjust or setup

PHP 5.5.24 running...

**Comment by Tramour** [comment]
No js errors.
OC log:
{"reqId":"VY26-FUNmgcAAHlOIyYAAAAM","remoteAddr":"217.227.18.175","app":"PHP","message":"Undefined offset: 0 at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-06-26T20:50:04+00:00"}
{"reqId":"VY26-FUNmgcAAHlOIyYAAAAM","remoteAddr":"217.227.18.175","app":"PHP","message":"touch(): Unable to create file \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/data\/owncloud.log because No such file or directory at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/log\/owncloud.php#60","level":3,"time":"2015-06-26T20:50:04+00:00"}
{"reqId":"VY27D1UNmgcAAHlrJO0AAAAP","remoteAddr":"217.227.18.175","app":"PHP","message":"Undefined offset: 0 at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-06-26T20:50:23+00:00"}
{"reqId":"VY27J1UNmgcAADmh-3oAAAAC","remoteAddr":"217.227.18.175","app":"PHP","message":"Undefined offset: 0 at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-06-26T20:50:47+00:00"}
{"reqId":"VY27MFUNmgcAAHlOI0oAAAAM","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:50:56+00:00"}
{"reqId":"VY27SlUNmgcAAHlNIs4AAAAK","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:51:22+00:00"}
{"reqId":"VY27alUNmgcAAHlqJLMAAAAO","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:51:54+00:00"}
{"reqId":"VY27oFUNmgcAAHlOI4AAAAAM","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:52:48+00:00"}
{"reqId":"VY28x1UNmgcAABRcDPUAAAAJ","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:57:43+00:00"}
{"reqId":"VY28zFUNmgcAAEzJTccAAAAF","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:57:48+00:00"}
{"reqId":"VY287lUNmgcAAEzJTc0AAAAF","remoteAddr":"217.227.18.175","app":"OCP\Share","message":"Sharing backend \OCA\Calendar\Share\Backend\Calendar not registered, \OCA\Calendar\Share\Backend\Calendar is already registered for calendar","level":2,"time":"2015-06-26T20:58:22+00:00"}
{"reqId":"VY287lUNmgcAAEzJTc0AAAAF","remoteAddr":"217.227.18.175","app":"OCP\Share","message":"Sharing backend \OCA\Calendar\Share\Backend\Event not registered, \OCA\Calendar\Share\Backend\Event is already registered for event","level":2,"time":"2015-06-26T20:58:22+00:00"}
{"reqId":"VY289lUNmgcAADmh-8gAAAAC","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T20:58:30+00:00"}
{"reqId":"VY29mlUNmgcAAHRzVr4AAAAH","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T21:01:14+00:00"}
{"reqId":"VY29olUNmgcAAHlqJQsAAAAO","remoteAddr":"217.227.18.175","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w011f6a8\/testoc\/owncloud\/lib\/private\/tempmanager.php#178","level":3,"time":"2015-06-26T21:01:22+00:00"}

**Comment by Tramour** [comment]
No ideas?

**Comment by codeling** [comment]
You mean you are missing calendar list on the left, correct?
I had the same problem just now; but only after pressing the top-left button in that same bar. The bar then will stay hidden and I haven't found a GUI Button yet to make it come back.

What I did find though was the setting that is responsible for this - it's a setting in the oc_preferences table where appid='calendar' and configkey='calendarnav'. Set that to 'true' to enable the calendar list again (you can do this e.g. via phpmyadmin if you're using mysql). Would be great if you could test if it's the same for you. Then we could change this issue into something like "Make button available for showing hidden calendar side-bar".

Edit: What I can confirm in addition to the missing possibility to un-hide the navbar, is the topmost buttons allowing to switch between the different views (day/week/month/:..) and between periods (next/prev week/month) to be missing (in latest master, downloaded today, i.e. https://github.com/libasys/ownCloud-8.1-Calendar-App/commit/f38cb1f7b709ca3f09584b844eb32a7bb505dfa2).

**Comment by Tramour** [comment]
There is no such config in my oc_preferences

There are just 2 entries:
choosencalendar 1
timezone Europe/Berlin

That's all. I'll add your line manually and report back... But I am missint the settings-button, the views. SImply all. Not just the calendars on the left side.

**Comment by Tramour** [comment]
Okay worked for the left part. See SC:
![screenshot 2015-06-28 20 45 53](https://cloud.githubusercontent.com/assets/13016794/8397749/c50c71f0-1dd6-11e5-9e6d-f760ddb0821c.png)

But still no settings and views.

What other entries are there in oc_preferences?

**Comment by Tramour** [comment]
Interesting: When I press the icon calendar left to "heute" the left side view vanishes again and in the database 'calendarnav' is set back to false!

**Comment by codeling** [comment]
> Interesting: When I press the icon calendar left to "heute" the left side view vanishes again and in the database 'calendarnav' is set back to false! 

Yes that was actually how I came to this issue ;)

**Comment by Tramour** [comment]
What are your settings in oc_appconfig for calendar? 
I have: 
enabled yes
installed_version 1.0.3
types 

As you can see configkey types is empty. Is that the same with your config?

**Comment by codeling** [comment]
In oc_preferences I have

```
calendarnav
currentview
extra_categories
timezone
```

The `chosenCalendar` is an interesting one, it might solve my other problem (https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/23)

In oc_appconfig, I have:

```
enabled     yes
installed_version   1.0.3
ocsid   168707
types
```

So yes, types is also empty for me.

**Comment by libasys** [comment]
@Tramour You have done a new installation of OC and a new installation of the calendar app? That wasn't a good idea! So your error logs says you have problems with your oc installation, missing file permissions, perhaps? you get some read, write errors! The update of the calendar app was for the OC 8.1rc1. I can't download and install every daily build of OC and test it!

**Comment by Tramour** [comment]
I can see your problem. But I still have 8.1rc1. It's just the daily build. What if I just started yesterday anyway? Then I would have downloaded the daily build and your app. And that is what I did...

Is there an "official" 8.1rc1 apart from the dailies?

Ok. This issue can be closed from my point of view.

**Comment by libasys** [comment]
Works the calendar app now? Short feedback please! Thanks.

**Comment by Tramour** [comment]
Unfortunately no. The settings in oc_preferences vanish/are set back as I posted before. And certain entries are missing like calendarnav and currentview anyway. 
I'm at work right now. I will DL the latest OC and try again this evening. May I will give 1.0.2. another try and try to upgrade to 1.0.3 after first initialisation.

**Comment by libasys** [comment]
ok! thanks for the feedback!

**Comment by Tramour** [comment]
I activated yout test account again on test.famibos.de. User and PW are the same as last time ;-)
If you want to take a look yourself...

**Comment by libasys** [comment]
ok thanks! i have a look into

**Comment by libasys** [comment]
```
opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/w011f6a8/testoc/owncloud/lib/private/tempmanager.php#178
```

means yout tmp directory has no write permission, you have to change the folder permission for "tmp"
I think with the current daily build of OC, they changed the z-index of the controls bar so the controls aren't visible!

**Comment by Tramour** [comment]
Hm. Ok. Test it this evening. But I thought a created a tmp-dir with www-user-access and implemented the path in config,php. I'll check it.

**Comment by libasys** [comment]
and this is the problem:

https://github.com/owncloud/core/blob/71e5bc180399e75af7b67b4187c19d94b5586a5f/core/css/apps.css#L413

you have to set the z-index to 40

```
#app-content {
    position: relative;
    height: 100%;
    overflow-y: auto;
    z-index:40;
}
```

So that wasn't a problem of the calendar app ;)

**Comment by Tramour** [comment]
Okay... How and where should I make the adjustments? Or is it a bug which will be fixed anyway in one of the next builds of core?

**Comment by Tramour** [comment]
Okay. Found where: apps.css. But for me it looked like a fix? So will it stay that way in final version of OC?

**Comment by libasys** [comment]
yes, i do a fix in the calendar app and enhance the z-index of the controls, but this take a while, btw after the first official release of oc 8.1! But for you testing this should work!

**Comment by Tramour** [comment]
Okidoki ;-)

**Comment by Tramour** [comment]
Works like a charm. Have a look youself ;-)
Why did they change the z-index it anyway?

**Comment by libasys** [comment]
to fix some other problems ^^

**Comment by Tramour** [comment]
Solved and closed. Thanks again.
