### ISSUE TITLE
Make more settings available via the WEB GUI dialog frontend when sharing a calendar.

### ISSUE THREAD

**Issue by farson2003** [libasys/ownCloud-8.1-Calendar-App#22]
This is with regards to the closed issue https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/9

@libasys made the configuration of a specific shared calendar possible with the share.config.js by id of the calendar! 

Thank you. That is excellent.

A marked improvement would be if all these settings could be managed directly via the WEB GUI frontend dialog when sharing a calendar.

**Comment by libasys** [comment]
@farson2003 this feature is for enhanced admins to setting up calendars! on a later version, it could be possible to integrate this in the web gui! but this is not the highest prior at the moment! We need a stable and working version with all the "main" features. If this is all running, than we can talk about to integrate such features. Thanks for your suggestion!
