### ISSUE TITLE
Javascript error and no dialog when trying to create new event

### ISSUE THREAD

**Issue by codeling** [libasys/ownCloud-8.1-Calendar-App#23]
In latest master, I just get this javascript error when trying to create a new event: 

```
TypeError: Calendar.calendarConfig.calendarcolors[calId] is undefined

'background-color': Calendar.calendarConfig['calendarcolors'][calId]['bgcolor']
```

The source for that error is in calendar.js, line 1802. The new event dialog does pop up if I comment out the $('.fc-select-helper').css(...) statement, but then there's a similar error later when closing the dialog:

```
TypeError: Calendar.calendarConfig.calendarcolors[elem.calendarid] is undefined

current_event[i].backgroundColor = Calendar.calendarConfig['calendarcolors'][ele...
```

(calendar.js, line 2183). Also commenting out this and the following two lines restores the ability to add and edit new events, but the background-color of the entry isn't correct.

Seems the chosen calendar (`Calendar.calendarConfig['choosenCalendar']`) isn't set (when I print it it's empty). No idea where this _should_ get set though.

**Comment by codeling** [comment]
Can be fixed by adding a row into oc_preferences, like this (replace user with your username):

```
INSERT INTO `owncloud`.`oc_preferences` (`userid`, `appid`, `configkey`, `configvalue`) VALUES ('user', 'calendar', 'choosencalendar', '1');
```

I suppose this is the "default calendar" that new entries get put into. How can I change this setting in the GUI? Shouldn't this be set automatically?

**Comment by libasys** [comment]
Hi @codeling by clicking on the colour field on the leftside bar where the calendars are! You see than a checkmark!

**Comment by codeling** [comment]
Ah yes, thank you! Seems this selection doesn't take hold under all circumstances (or can get lost with an upgrade)? I don't know exactly why it wasn't set in my case.
A a fallback, can I suggest to automaticaly set it to the first calendar, if it isn't set?

**Comment by libasys** [comment]
this should the default behaviour, but perhaps if you delete the choosen calendar, there should be a fallback to set!

**Comment by codeling** [comment]
Hm I haven't deleted any calendar. I only updated the calendar app, and then noticed this. The database entry in oc_preferences was missing, I had to add it manually

**Comment by libasys** [comment]
What of version of OC do you installed? the other problem could be identified by reducing a z-index value! to show the top controls bar! But by default the first calendar have the choosen parameter

**Comment by codeling** [comment]
~~master from yesterday. Not sure exactly which commit ;)~~ nightly build from 28th of June.
Yup will try the z-index fix later today or tomorrow. Thanks a lot for the fast support!
