### ISSUE TITLE
Posibillity of choosing Groups

### ISSUE THREAD

**Issue by SvenVoet** [libasys/ownCloud-8.1-Calendar-App#3]
Hello.
It is possible to choose the Groups, to show in the Calendar or not? 

If i´m Admin, or a "Groupleader" can see the Calendar of 4 or 5 groups. With 5 People in every Group, to it would be nice, if i can choose the Group which should be displayed in the Calendar. So the Groupleader can better see, which persons in this Group are free at the Date.

**Comment by libasys** [comment]
Hi @SvenVoet,
at the moment this feature request is not possible, we have to test all the implemented new features of that version of calendar! But your suggestion sounds interesting, needs a discussion and a plan "how to get this feature to work"!  Thanks for your suggestion!

**Comment by SvenVoet** [comment]
Hello libasys. 
Thanks for answer. The suggestion is (for me) just the following. To this time, it is possible to make some Groups in the Kalender. I will name them for this diskussion just "Group 1" to "Group 5" 
I use the owncloud with your Calender (to this time in Version 8.0) to plan some peoples work, to see which person is free at a specific date. So i have all the People in the Calender.

I´m from Germany, so the Groups are for me specific Parts of Germany. Like North-West, North, South and so on. And if i search a specific Person from the South of Germany, i have to look, who is in the Group "South".

At the left side, you can show all shared Persons/Calendars with the Colors. If there would be a Dropdown Menu, with all the stored Groups... So if i select a specific Group, only the Persons in this Group will shown in the Calender... That would be nice. And gives a better Overview when you have some more shared Calendars to work with..
