### ISSUE TITLE
Enhancement: Sharing calendar with public link: Make view unchangeable 

### ISSUE THREAD

**Issue by farson2003** [libasys/ownCloud-8.1-Calendar-App#5]
Many organizations/companies would very much use the "sharing a calendar with a public link" feature, i.e. to send it to individuals, groups, or even to embed a public “read only” calendar on an organization's website.

When sharing a calendar with a public link in some scenarios it might be beneficial to "fix" the view, i.e. to a list view, so viewers of the shared public calendar cannot change it. 

Such option when sharing a calendar via a public link would be of benefit, especially when embedding it on a company's website.

**Comment by libasys** [comment]
https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/9
