### ISSUE TITLE
Error when sharing a public calendar and sharee views calendar in list view: Entries disappear

### ISSUE THREAD

**Issue by farson2003** [libasys/ownCloud-8.1-Calendar-App#6]
When sharee of public link clicks on "List view" of calendar all events/calendar entries disappear.

Steps to reproduce:
1. Log in to system , i.e. to demosite https://ssl.webpack.de/demo81.libasyscloud.de/
2. Share a calendar via public link (i.e. https://ssl.webpack.de/demo81.libasyscloud.de/index.php/apps/calendar/s/WkR7R2np3Vz67bm   )
3. Sharee then goes on public link and views public calendar. 
4. Sharee then clicks on "List view" of calendar.
5. Error: All events/calendar entries disappear suddenly and cannot be recovered until the page is refreshed.

**Comment by libasys** [comment]
fixed!
