### ISSUE TITLE
Sharing calendar with public link: Do not show "little monthly calendar"

### ISSUE THREAD

**Issue by farson2003** [libasys/ownCloud-8.1-Calendar-App#7]
Enhancement: Sharing calendar with public link: Make "little monthly calendar" disappear 

Many organizations/companies would very much use the "sharing a calendar with a public link" feature, i.e. to embed a public “read only” calendar on an organization's website.

When sharing a calendar with a public link in some scenarios it might be beneficial to disable the  "little monthly calendar" on the view for the sharee.

Such option when sharing a calendar via a public link would be of benefit, especially when embedding it on a company's website.

**Comment by libasys** [comment]
https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/9
