### ISSUE TITLE
Improvements for public link sharing of calendar

### ISSUE THREAD

**Issue by farson2003** [libasys/ownCloud-8.1-Calendar-App#9]
I made a number of feature requests with the aim to individualize options for a sharer when sharing a public calendar via link:
1. Disable "little monthly calendar" for sharee (https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/7)
2. Make view unchangeable (https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/5)
3. Make timezone unchangeable (https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/4)
4. Allow sharer to choose limit timespan to be viewed by sharee (https://github.com/libasys/ownCloud-8.1-Calendar-App/issues/8)

Please consider.

**Comment by sahne123** [comment]
All this changes are focused on embedding the calendar on a website via iframe. I dont think it's made for such purpose. Don't know if this is a really good idea.

In my opinion it's a better way to access the calendar via webcal / ical and customize it on your own application/website. There are also plenty plugins to import ical feeds for common content management systems.

**Comment by libasys** [comment]
@farson2003 i added a global config file for enhanced view options public sharing via link!
https://github.com/libasys/ownCloud-8.1-Calendar-App/blob/master/calendar/js/share.config.js
So the admin of a owncloud can setup some options like,
- show small calendar
- show timezone select box
- show footer, header
- first day of week init
- defaultView
- active calendarViews incl. prev, next buttons

**Comment by libasys** [comment]
New version is available! Now you can configure directly a shared calendar with the share.config.js by id of the calendar! The id is shown up in the calendar settings dialog!
